supabase/ui

src/components/Badge/Badge.css
=> chore: improved <Badge> colors for dark mode

README.md, src/components/Loading/Loading.stories.tsx, src/components/Loading/Loading.tsx, src/components/Loading/index.tsx, src/components/Loading/loading.css, src/index.tsx
Loading component can be wrapped around any `Rea…ct.ReactNode`
=> feat: <Loading> component added

src/components/Input/Input.tsx, src/components/Select/Select.tsx
feat: add `autofocus` prop to Input, Select and TextArea
• also some tidying, reordering of some lines
in use:
```javascript
<Input autofocus label="first name"/>
```
=> feat: add `autofocus` prop to Input, Select and TextArea.

src/components/Auth/Auth.tsx, src/components/Input/Input.tsx
Input onChange prop updated to send native onChange event.
cc @phamhieu @joshenlim 
example below of how to use new onChange using `e.target.value` to get value
```js
<Input
type="password"
onChange={(e) => setPassword(e.target.value)}
/>
```
=> feat: Input now sends onChange event, not just e.target.value

src/components/Menu/Menu.tsx, src/components/Typography/Typography.css, src/components/Typography/Typography.tsx
Fix for the `max-width` rule being applied for every typography component: `Typography.Title`, `Typography.Text` and `Typography.Link`
Consider using Typography component as wrapper if child content should have limited width
Every typography component has limited width by default
For example it prevents links at the bottom of `Auth` component from being properly aligned on wide screens
http://ui.supabase.com/?path=/story/auth-auth--default
`max-width` is only applied to the `Typography` root component. We can wrap other items in `Typography` if we need to set `max-width`
That's also fixing an issue with `Auth` links
N/A
=> Isolate max-width style to container

package.json
Bug fix.
npm was ignoring `dist` because in absence of the `files` property in
package.json or .npmignore, it uses .gitignore instead, which ignores `dist`.
Closes #118.
=> fix(release): add files array to package.json

src/lib/Layout/FormLayout/FormLayout.module.css
horizontal forms now take up 1/3 width lab…el, 2/3 width input
before:
after:
=> fix: adjust column width 

src/components/Auth/Auth.tsx, src/components/Input/Input.tsx
When switching between sign in and sign up any already entered data data is now persisted
Done by lifting the state getter and setters of the inputs fields one level up (to Auth) and passing it down as props to EmailAuth
Had to modify the Input component to take a default value, so we can have it prefilled, since we are mounting and unmounting it on view change.
=> fix: persist form data when switching views

src/components/Dropdown/Dropdown.tsx, src/components/Modal/Modal.module.css, src/components/Modal/Modal.tsx, src/components/SidePanel/SidePanel.module.css, src/components/SidePanel/SidePanel.tsx, src/components/Transition/Transition.tsx, src/lib/Overlay/Overlay.module.css, src/lib/Overlay/Overlay.tsx, src/types.ts
• lib was relying on external tailwind css for animations before hand, now the default css classes are added into components
• using props `transition` and `transitionOverlay` its possible to pass your own css classes in for enter, enterFrom, enterTo, leave, leaveFrom and leaveTo, which will override the default css
=> fix: added transition CSS into the library

package.json
Use latest React version and lift React v17 restriction
This closes #149.
=> Update to React 17.0.1

README.md
Saw there was a spelling mistake on the website, [made a fix there](https://github.com/supabase/supabase-ui-web/pull/3)
came to check the repo out and saw the mistake here too. Thought I'll push a quick fix 😅
=> Fixes a small spelling mistake (Themeing -> Theming)

src/lib/Overlay/Overlay.tsx
Bugfix
https://github.com/supabase/ui/issues/159#issuecomment-812804817
Now you can freely change the visibility of the Dropdown component without having the loop error.
<p align="center">
</p>
=> Fix: Prevent loop when changing the visibility on Dropdown

src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx
Button now supports a `as` string prop which allows for any element tag to be used which replaces the `<button>` tag
fixes #192
```JS
<Button as="span">Custom tag button</button>
```
=> feat: custom tag option for Button component

src/components/Dropdown/Dropdown.module.css
Ensure that dropdown radio items have consistent spacing (basically emulated how radix UI implemented it)
=> fix: dropdown radio padding for item indicator

package-lock.json, src/components/Dropdown/Dropdown.module.css, src/components/Dropdown/Dropdown.tsx
Feature
- Closes #198 
Added arrow as a boolean prop to dropdown
Adjustment to border rounded styles on align start or end is made using individually rounding corners. Example here with align `start` and side `bottom`
=> ptch: add arrow property and styles in dropdown

src/components/InputNumber/InputNumber.module.css, src/components/InputNumber/InputNumber.stories.tsx, src/components/InputNumber/InputNumber.tsx
Bug fix - resolves https://github.com/supabase/grid/issues/20
None, the arrows were removed because of https://github.com/supabase/grid/issues/20
Fixed the visual glitches seen in the issue above and now they work with controlled inputs
=> fix: inputnumber arrows

rollup.config.js
Bugfix
When you try to run the `npm run build` script, you get the following error on your terminal:
> [!] Error: Could not resolve entry module (src/components/Accordian/index.tsx).
Error: Could not resolve entry module (src/components/Accordian/index.tsx).
at error (/home/angelmtztrc/Documents/repositories/ui/node_modules/rollup/dist/shared/rollup.js:5305:30)
at ModuleLoader.loadEntryModule (/home/angelmtztrc/Documents/repositories/ui/node_modules/rollup/dist/shared/rollup.js:18552:20)
at async Promise.all (index 8)
Now, you can execute the `build` script without any problem.
> (!) Circular dependencies
src/index.tsx -> src/components/Modal/index.tsx -> src/components/Modal/Modal.tsx -> src/index.tsx
src/index.tsx -> src/components/SidePanel/index.tsx -> …
=> fix: Could not resolve entry module `src/components/Accordian/index.tsx`

src/components/Checkbox/Checkbox.module.css, src/components/Checkbox/Checkbox.stories.tsx, src/components/Checkbox/Checkbox.tsx, src/components/Input/Input.stories.tsx, src/components/Input/Input.tsx, src/components/InputNumber/InputNumber.tsx, src/components/Radio/Radio.module.css, src/components/Radio/Radio.stories.tsx, src/components/Radio/Radio.tsx, src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx, src/components/Toggle/Toggle.stories.tsx, src/components/Toggle/Toggle.tsx, src/components/Upload/Upload.tsx, src/lib/Layout/FormLayout/FormLayout.module.css, src/lib/Layout/FormLayout/FormLayout.tsx
Feature - resolves https://github.com/supabase/ui/issues/16
None
`beforeLabel` and `afterLabel` props added to all inputs
=> feat adds beforeLabel and afterLabel props

src/components/Auth/Auth.tsx
fixes #193 
Just exposes the `update_password` component in the UI Auth in the view map so it can be conditionally shown with the view prop.
=> fix: expose the update_password component as a view

src/components/Auth/Auth.tsx
fixes: #73
This commit will allow displaying the verification message on signup when email verification is enabled.
=> fix: display email verification message on sign up

src/components/Badge/Badge.test.js
**Description**
Add tests for `<Badge />` component, with no production code changes.
**Changelog**
**Additional**
=> test: render tests for badge component

src/components/Auth/Auth.tsx
Bug fix
also removed unreachable break statements
component works as expected
=> auth component now returns null on default case

src/components/Auth/Auth.tsx, src/components/Typography/Link.tsx
Fixing an issue with keyboard accessibility of anchor links in `Auth` component. Updating `Auth` to have `Typography.Link` utilize `href` attribute, and add `id`'s to the various auth forms for semantical correctness.
- ~~Added `keyDownHandler()` in the `Link` component in order to enable activating with a keyboard (using `Space` or `Enter` - same as default `button` behaviour)~~ EDIT: This was reverted
- Updated `EmailAuth` to take in a new `id` prop (which is then assigned as `id` attribute on the `form`)
- Updated all auth views to specify an `id` attribute on forms
- Updated all `Typography.Link`'s in `Auth` to provide an `href` attribute, referencing the appropriate `id` from above (ie. `#auth-forgot-password`, `#auth-magic-link`, etc.)
Closes #256
When navigating with a keyboard …
=> fix: [#256] a11y issue with links in Auth

src/components/Auth/UserContext.tsx
Feature/bug fix - hard to tell!
When you use the UserContext, you will get a flash of "unauthenticated" state, which immediately changes to a logged in state if the user has a cached session in localStorage. This flash is quite visually tearing, and there doesn't seem to be any way to check "session info is being loaded" to show an intermediate state either.
One could argue that this at least provides renderable identity between client and server - since the server won't have any cached session, the session will be `null` on the server but potentially a cached value on the client, leading to warnings about mismatching HTML trees.
Instead of setting the initial session state in a `useEffect` (to make it only apply on the client), this PR moves it to the initial hook setup. This ensures …
=> feat: optimize loading of cached session

README.md
Update of `README.md` to fix some broken markdown-syntax.
The strikethrough (`~~`) includes the list and checkbox (`- [ ]`), resulting in neither the list, nor the checkbox, being rendered correctly.
```md
~~- [ ] Layout~~
~~- [ ] Grid (Flex)~~
```
By moving the `~~~` to after the `- [ ]`, the markdown renders properly.
`~~- [ ] Layout~~` becomes `- [ ] ~~Layout~~`
```md
```
=> fix: README markdown formatting

src/components/Auth/Auth.tsx
Use the correct parameters returned by auth.signUp(). If user object is
returned and session is null, then display message to check email for
the confirmation link.
Bug fix for email auth signup confirmation message.
[Please link any relevant issues here.](https://github.com/supabase/ui/issues/319)
Corrected behavior for email auth signup.
=> Fix(Auth): display email confirmation message after signup

src/components/Input/Input.tsx
Necessary for supabase/supabase#5403, which dynamically updates `reveal`.
=> fix: only check `hidden` if `reveal` is true, to correctly handle `reveal` changes

src/components/Auth/Auth.tsx
Now `<Auth providers={['slack']} supabaseClient={supabase} />;` throws an error as `SocialIcons` has no function for some social providers (slack, spotify, linkedin, notion).
Missing social provider icon should not break Auth component.
=> hotfix: Auth component could not be used for Slack, Spotify, Linkedin or Notion.
