- package-lock.json
- package.json
- src/components/Toggle/Toggle.js
- yarn.lock
removed dependency not used.
also should bump minor release version on npm registry.
> fix: remove dependency and force a release

- package-lock.json
- package.json
Running `npm run storybook` was throwing a `Error: Cannot find module 'react/package.json` message.
Adding react-dom as a dev dependency fixes this.
> Add react and react-dom as dev dependency

- src/components/Checkbox/Checkbox.stories.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/Checkbox/CheckboxContext.tsx
- src/components/Radio/Radio.tsx
• `<Checkbox.Group>` now supports option prop rather than using sub components
• `checked` prop added to <Checkbox>
> fix: Checkbox fixes

- src/components/Checkbox/Checkbox.tsx
- src/components/Input/Input.tsx
- src/components/Radio/Radio.tsx
- src/components/Select/Select.tsx
checkbox and radio now have working 'checked' props
fixes #37
> Fix/checkbox checked prop & onChange now working correctly for Input, Select, Checkbox and Radio

- .gitignore
- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
Support Button component with forwardRef
> fix: button with forwardRef 

- src/components/Icon/Icon.stories.tsx
- src/components/Icon/Icon.tsx
- src/components/Toggle/Toggle.stories.tsx
> chore: add in fill and stroke props to <Icon> component

- src/components/Checkbox/Checkbox.css
> fix: checkbox selectors updated

- src/components/Auth/Auth.stories.tsx
- src/components/Auth/Auth.tsx
- src/components/Auth/UserContext.tsx
Adds the `Auth.UserContextProvider` component, which us used to track user and session state:
Signed out:
Signed in:
> feat: add auth component usercontext

- src/components/Modal/Modal.css
- src/components/Modal/Modal.js
- src/components/Modal/Modal.stories.js
fixes Modal styling which was breaking
> fix: Modal css styling fixed. also adjusted colors slightly and layout.

- src/components/Modal/Modal.css
- src/components/Modal/Modal.js
- src/components/Modal/Modal.stories.js
also,  `title` and `description` defaults being set by mistake
before:
after:
> fix: modal icon was in wrong position.

- src/components/Toggle/Toggle.stories.tsx
- src/components/Toggle/Toggle.tsx
- src/lib/Layout/FormLayout/FormLayout.css
- src/lib/Layout/FormLayout/FormLayout.tsx
new layouts:
fixes #67 
fixes #45
> fix: <Toggle> component fixed to support left and right align

- src/components/Typography/Text.css
- src/components/Typography/Text.tsx
- src/components/Typography/Typography.stories.tsx
> fix: <Typography.Text> renders text correctly without <span> tags. 

- src/components/Button/Button.tsx
- src/components/Modal/Modal.css
- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.tsx
> feat: Close button added, which can be shown with new prop `closable`

- src/components/Auth/Auth.css
- src/components/Auth/Auth.tsx
> fix: auth layout issues and icon color issue

- src/components/Button/Button.tsx
- src/components/Tabs/Tabs.css
- src/components/Tabs/Tabs.stories.tsx
- src/components/Tabs/Tabs.tsx
- src/components/Tabs/TabsContext.tsx
- src/components/Tabs/index.tsx
- src/index.tsx
> WIP feature/Tabs

- src/components/Icon/Icon.stories.tsx
- src/components/Icon/Icon.tsx
> feat: added new `src` prop, for inserting SVG files into `<Icon>`

- src/components/Space/Space.tsx
- src/components/Tabs/Tabs.css
- src/components/Tabs/Tabs.stories.tsx
- src/components/Tabs/Tabs.tsx
`addOnBefore` and `addOnAfter` props added to `<Tabs>`
> Feature/ addOnBefore and AddOnAfter for <Tabs> tab bar

- src/components/Dropdown/Dropdown.css
- src/components/Menu/Menu.css
- src/components/Menu/Menu.stories.tsx
- src/components/Menu/Menu.tsx
• `active` prop added to show an active state
• also added `rounded` prop to show rounded background
• adjusted background colors of Menu and Dropdown
> feat: add `active` prop to `<Menu.Item>`

- src/components/Dropdown/Dropdown.css
- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Menu/Menu.tsx
fix: add styles and className props to Dropdown
> fix: add styles and className props to Dropdown

- README.md
- development.md
> chore: update readme

- README.md
Did you mean 'supabaseClient'?
> fix: possibly typo error

- src/components/Auth/Auth.stories.tsx
- src/components/Auth/Auth.tsx
can now control what view is shown in Auth component 
fixes #122
> fix: allow for view overriding | fixes #122

- src/components/Checkbox/Checkbox.module.css
> fix: lightmode checkbox color

- src/components/Button/Button.module.css
> fix: remove button :focus styles.

- src/components/Input/Input.tsx
• the following is now supported on Input
onFocus
onBlur
onKeyDown
Bug fix, feature, docs update, ...
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.
> feat: add new html props

- README.md
Readme update syntax error fix
> README: Correct missing closing tag

- src/components/Alert/Alert.module.css
- src/components/Alert/Alert.stories.tsx
- src/components/Alert/Alert.tsx
- src/components/Alert/index.tsx
- src/components/InputNumber/InputNumber.stories.tsx
Alert component. #108 
With icons:
With close icon:
> feat: Alert component

- docs/spec.json
- package-lock.json
- src/components/Dropdown/Dropdown.tsx
- src/lib/Overlay/Overlay.module.css
- src/lib/Overlay/Overlay.tsx
- Replace **topCentre** by **topCenter** in `components/dropdown/Dropdown.tsx`, `lib/Overlay/Overlay.tsx, `lib/Overlay/Overlay.module.css` and in `docs/spec.json`
- Shorten `import { AnimationTailwindClasses } from './../../types'`  to `import { AnimationTailwindClasses } from '../../types'` in  `lib/Overlay/Overlay.tsx, `
docs update, ...
> Replace topCentre by topCenter

- src/components/Modal/Modal.tsx
> Clean Modal.tsx

- src/components/Modal/Modal.module.css
- src/components/Modal/Modal.tsx
• also fixed centre align issue on the modal content
> fix: accessible modal added

- package-lock.json
- package.json
- rollup.config.js
- src/components/ContextMenu/ContextMenu.module.css
- src/components/ContextMenu/ContextMenu.stories.tsx
- src/components/ContextMenu/ContextMenu.tsx
- src/components/ContextMenu/index.tsx
- src/index.tsx
• Added context menu
can trigger by right clicking an area of the `children` area.
• Uses same structure as the Dropdown component
> Feat: Context Menu

- package-lock.json
- rollup.config.js
- src/components/Image/Image.module.css
- src/components/Image/Image.stories.tsx
- src/components/Image/Image.tsx
- src/components/Image/index.tsx
- src/index.tsx
This PR adds a intial support for image component in Supabase-UI, It has little features like avatar and responsive
Haven't found any issue on StoryBook, Will work more over it and add more features
Image component functions well with avatar and normal type and  a special responsive functionality
I would be furthur working over this feature and implementing more usable props and features.
[Normal Image](https://i.imgur.com/sOg21Ag.png)
[Circle Image](https://i.imgur.com/4v5B1nH.png)
> patch: Added Image component with basic functionalities

- package-lock.json
- src/components/Image/Image.module.css
- src/components/Image/Image.stories.tsx
- src/components/Image/Image.tsx
Previous implementation has hard coded CSS, now switched to tailwindcss.
Everything introduced is working
> improvement: Added rounded type and fixed styles

- package-lock.json
- package.json
- src/components/Auth/Auth.stories.tsx
- src/components/Auth/Auth.tsx
> fix: add in redirectTo prop for Auth component

- src/components/Auth/Auth.stories.tsx
- src/components/Auth/Auth.tsx
- src/components/Auth/Icons.tsx
Adds Apple OAuth button 
#195
As seen in Supabase UI Storybook
> feat(ui/auth): adds Apple OAuth button

- src/components/Button/Button.test.js
**Description**
Add tests for `<Button />` component, with no production code changes.
**Changelog**
**Additional**
> test: render tests for button component

- src/components/Input/Input.tsx
• extend html input attributes in props
> fix: extend Input props

- rollup.config.js
- src/components/Avatar/Avatar.module.css
- src/components/Avatar/Avatar.stories.tsx
- src/components/Avatar/Avatar.tsx
- src/components/Avatar/index.tsx
Implemented initial support for Avatar Component. Testing AvatarGroup component and Icons too.
> feat: Implemented initial support for Avatar Component

- src/components/Avatar/Avatar.module.css
> Fix CSS key typo

- src/components/Checkbox/Checkbox.module.css
Just noticed this typo. Thanks for maintaining this great library <3
> Fix invalid CSS key

- package-lock.json
- package.json
- src/components/Dropdown/Dropdown.module.css
- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.tsx
• added nested dropdown functionality from Radix
> feat: nested dropdowns

- src/components/Button/Button.module.css
- src/components/Button/Button.tsx
- src/components/Input/Input.module.css
- src/components/Input/Input.stories.tsx
- src/components/Input/Input.tsx
- src/components/InputNumber/InputNumber.module.css
- src/components/InputNumber/InputNumber.tsx
- src/components/Listbox/Listbox.tsx
- src/components/Listbox/SelectStyled.module.css
- src/components/Listbox/SelectStyled.stories.tsx
- src/components/Select/Select.module.css
- src/components/Select/Select.tsx
- src/components/Textarea/Textarea.css
- src/components/Textarea/Textarea.js
Adds borderless inputs and textAlign prop to button
> Feat: Borderless inputs and textAlign prop on button

- src/components/Upload/Upload.stories.tsx
- src/components/Upload/Upload.tsx
Extended the present functionality of the `Upload` component. (Issue #254)
The `Upload' component didn't support 'tracking'/retrieval of the uploaded files.
• Added two props: files and setFiles which allow you to control the uploaded files using state from a parent component.
• Added previews for uploaded images in the story.
> WIP: Extend functionalities of the Upload component

- .github/workflows/docs.yml
- .github/workflows/release.yml
updating workflows to use node 14
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.
> chore: update workflows to use node v14

- src/components/Tabs/Tabs.tsx
• tabs has been remade with radix on another branch so this will be removed soon
Bug fix, feature, docs update, ...
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.
> hotfix: fix: quick fix for tabs content.

- src/components/Tabs/Tabs.tsx
> fix: force release

- src/components/Listbox/Listbox2.tsx
- src/components/Listbox/SelectStyled.stories.tsx
Resolves https://github.com/supabase/ui/issues/338
> fix: prevent on select if disabled for listbox option

- package-lock.json
- src/components/Badge/Badge.stories.tsx
- src/components/Badge/Badge.test.js
- src/components/Badge/Badge.tsx
Bug fix
Currently there is no easy way to customize the badge component.
Also needed for styling the inner contents of the badge, otherwise would have to wrap the child in additional tags.
#339 
Added overlayClasses prop which can accept class names as string and apply to Badge
```
<Badge overlayClasses=" border-teal-50 border-2">
Hello world
</Badge>
```
Styling of inner content can be done by passing span element with custom styles.
> fix: added className Prop.

- development.md
An extremely cosmetic docs update to the `development.md` file.
> Doc: Make 'Common Issues' scripts to be run more visible.

- src/components/Modal/Modal.tsx
Bug fix, feature, docs update, ...
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.
> add radix props to modal
